default_stages: [pre-push]
default_language_version:
  python: python
repos:
- repo: local
  hooks:

  - id: black
    stages: [pre-commit,pre-push]
    name: Format source using black
    entry: pipenv run black -q
    files: "^src/.*\\.py$"
    require_serial: true
    language: system

  - id: isort
    stages: [pre-commit,pre-push]
    name: Sort imports
    entry: pipenv run isort
    files: "^src/.*\\.py$"
    require_serial: true
    language: system

  - id: flake8
    stages: [pre-commit,pre-push]
    name: Check for programming errors
    entry: pipenv run flake8
    files: "^src/.*\\.py$"
    require_serial: true
    language: system

  - id: mypy
    stages: [pre-commit,pre-push]
    name: Check for type errors
    entry: pipenv run mypy --no-error-summary
    files: "^src/.*\\.py$"
    require_serial: true
    language: system

  # - id: rst-lint
  #   stages: [commit,push]
  #   name: Lint ReStructuredText files
  #   entry: pipenv run rst-lint
  #   files: "^docs/source/.*\\.rst$"
  #   language: system